server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/megrow_database
    username: megrow_admin_user
    password: megrow_admin_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC